# Instructions

1. Create a variable called `slp_cat_wkday` categorizing weekday sleep.
2. Subset the dataset to only include people with missing values.
2. Remove non-sleep-related variables from the dataset.
4. Call your finished dataset `missing_sleep`.

```{r}
nlsy <- mutate(nlsy, slp_cat_wkdy = case_when(
  sleep_wkdy < 5 ~ "little",
  sleep_wkdy < 7 ~ "some",
  sleep_wkdy < 9 ~ "ideal",
  sleep_wkdy < 12 ~ "lots",
  TRUE ~ NA_character_))
missing_sleep <- filter(nlsy, is.na(slp_cat_wkdy))
missing_sleep <- select(missing_sleep, starts_with("slp"), contains("sleep"))
missing_sleep
```

---
class:inverse
# Exercises 1
.center[
<iframe src="https://giphy.com/embed/aSZSj0mT8f6tW" width="240" height="233" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/dog-chores-aSZSj0mT8f6tW"></a></p>
]
1. Follow the instructions on the previous slide using pipes. (The code on the previous slide is provided in today's script.)
2. Experiment with switching up the "order of operations". Can you complete the instructions in a different order and get the same result? Can you think of a situation when you might not be able to do so?


---
class:inverse
# Exercises 2
.center[
<iframe src="https://giphy.com/embed/dsKnRuALlWsZG" width="480" height="271" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/the-office-steve-carell-michael-scott-dsKnRuALlWsZG"></a></p>
]


1. Among the only children, find the correlation between hours of sleep on weekdays and weekends.
2. Create a variable that is 1 if an observation has an income between 20,000 and 30,000, and 0 otherwise. Calculate the proportion of people in the dataset who fit that criterion.
3. Recreate the `summary()` function using `summarize()` (i.e., produce all the same statistics for a variable of your choice.)


class:inverse
# Exercises 3
.center[
<iframe src="https://giphy.com/embed/IXB6mQUgOqWQM" width="360" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/make-count-withcount-IXB6mQUgOqWQM"></a></p>
]

1. Find the median income per region. Before doing so, make sure that you've made region into a factor variable with appropriate names so we can easily read your results.
2. Calculate and compare the median income for people who sleep at least 8 hours on weekdays and those who sleep less.
3. Among the women (`sex = 2`), calculate the proportion who live in each region.

class: inverse
# Exercises/challenge

1. Apply the following inclusion criteria to the NLSY dataset to make a analysis dataset: from region 1 or 4, with at least 2 siblings, and doesn't wear glasses.
2. Make a variable in that dataset that categorizes people in quartiles (split at 25th, 50th, and 75% percentiles of the new dataset) by income. Make sure the categories have descriptive names.
3. Make a table 1 for this new dataset, stratified by the new income variable. Make sure they show up in the correct order in your table. Include p-values testing across strata but only print 2 digits for them. Perform an exact test for the region comparison.
4. (Challenge) Make a nice-looking table 1 for some data you are working with or have access to!

---